### ISSUE TITLE
How to build project for a non-default filepath?

### ISSUE THREAD

**Issue by superrpotion** [zaksabeast/DreamRadarCartRedirect#14]
Hello, I have my NDS saves stored in /roms/1. nds/1. Physical/saves/Pkmn_BLK-Loose.sav, not /roms/nds/saves/black.sav. 

Is there a step-by-step guide on how to build a .ips file for Luma with a custom filepath? I’m not seeing a build guide in readme, just the commands I’m supposed to modify. I have access to both a Windows or a Mac PC, but I don’t have Python installed on either one. Thanks in advance.

**Comment by zaksabeast** [comment]
1. Clone the repository
2. Dump the `.code` file of your game using [GodMode9](https://github.com/d0k3/GodMode9) (launch GodMode9, mount your game, open the `exefs` directory, and `.code` should be there)
3. Copy the `.code` file to the cloned repository directory on your computer as `code.bin`
4. Download [armips](https://github.com/Kingcom/armips)
5. Run the command from the readme using your save file to produce `code_patched.bin`
6. Optionally download [flips](https://github.com/Alcaro/Flips) and run `flips -c code.bin code_patched.bin code.ips`

Step 6 is optional since Luma can use a patched `code.bin` file (just make sure to rename it from `code_patched.bin` to `code.bin` when copying to your 3ds).  Flips doesn't have pre-built releases, so you'd have to compile it yourself.
