### ISSUE TITLE
SyntaxError: invalid syntax at line 93

### ISSUE THREAD

**Issue by TheUnoveanSnivy** [zaksabeast/DreamRadarCartRedirect#2]
Hello!
Thank you very much for taking the time to code this. However, when I tried to follow the instructions of the readme file all I got was an Invalid Syntax Error at Line 93 when trying to run the "python poke_redirect.py -h" script. Thank you very much!

![Syntax Error 93](https://user-images.githubusercontent.com/80992148/111852949-446b4300-8919-11eb-833f-e491428edba8.png)

**Comment by zaksabeast** [comment]
Hello!  I wrote the original patch in assembly, but DRayX is the one who added the python script.

That said, I believe this issue is caused from using Python 2, and the script requires Python 3.  Could you try running `python --version` and see if you're using 2 or 3?

If you're using 2, try installing 3 and see if that fixes the issue.

**Comment by TheUnoveanSnivy** [comment]
That fixed it! Had Python 2.7 as the default. I'll try to figure out the other steps from here. Thank you very much!
