### ISSUE TITLE
What is the Poketransporter patch for?

### ISSUE THREAD

**Issue by SokroKalimi** [zaksabeast/DreamRadarCartRedirect#21]

**Comment by zaksabeast** [comment]
The Transporter patch does the same thing as the Dream Radar patch.  Instead of reading/writing a gen 5 save from a cartridge, it reads/writes from the sd card instead.  If a save is not present, it thinks a cartridge is not present.

Transporter asks the user to select from a list of games, then transfers Pokemon from the selected game to Bank.  If you use this patch and have a gen 5 save file exists on your sd card, it will show up in the list of games and transfer Pokemon from the sd save file.
