### ISSUE TITLE
Flips can't read ROM when building patch

### ISSUE THREAD

**Issue by Chaaboy** [zaksabeast/DreamRadarCartRedirect#29]
When putting in flips command it says i cant read the rom

**Comment by zaksabeast** [comment]
It sounds like flips can't find the file you're making the patch from, which suggests the file name you typed is inaccurate or the file path is inaccurate.

[Make sure you dumped the `.code`](https://github.com/zaksabeast/DreamRadarCartRedirect?tab=readme-ov-file#------dumping-the-code---), opened a terminal in the folder containing the `.code` file, and double check to make sure there aren't any typos in the command.

**Comment by Chaaboy** [comment]
.code should be renamed to transporter.bin correct?

**Comment by zaksabeast** [comment]
Yep, that's correct.

**Comment by Chaaboy** [comment]
![out](https://github.com/user-attachments/assets/81ed8683-e704-4b66-bf98-f1f7a6b6f241)
![terminal](https://github.com/user-attachments/assets/505e54a9-9fde-4acd-9c35-0b9ed2f2fad3)

**Comment by zaksabeast** [comment]
The armips command should make a `transporter_patched.bin` file, but that doesn't look like it exists.

You also need the `sd-save-utils.s` file from the repository.  Instead of copying the repository files to `gm9\out`, try copying the `transporter.bin` to the repository and running the commands from there.  That will make sure all of the files you need will be present.

One more note, update the `SD_SAVE_PATH` path so that `\`s are `/`s, and remove the leading `D:`.

**Comment by Chaaboy** [comment]
im geussing the problem is armips, i could not figure out how to download it from github

**Comment by Chaaboy** [comment]
how do i get armips off github, when i downoad reposiotry it say command ./ armips dosent work

**Comment by zaksabeast** [comment]
Download armips from here: https://github.com/Kingcom/armips/releases/tag/v0.11.0

**Comment by Chaaboy** [comment]
i downloaded new armips and flips and transporter_patched was not created when entering command
